name = "bindings-remix"
type = "javascript"

account_id = ""
workers_dev = true
main = "./build/index.js"
compatibility_date = "2022-05-13"

[site]
bucket = "./public"

[build]
command = "DEPLOY=true npm run build"

[build.upload]
format="service-worker"

[[unsafe.bindings]]
name = "BINDEE"
type = "service"
service = "bindings-remix-bindee"
environment = "production"
